services:
  playwright-tests:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: playwright-allure-runner
    ipc: host
    working_dir: /app
    ports:
      - '4040:4040'
    environment:
      - BROWSER=Chrome
    volumes:
      - ../:/app
      - /app/node_modules
      - ../reports/allure:/app/reports/allure
    command: >
      sh -c "
            npx playwright test;
            exit $$?"
