name: Playwright Tests
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  playwright-tests:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image with Cache
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          load: true
          tags: docker-playwright:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Start Containers And Run Tests
        working-directory: ./docker
        run: docker compose up --exit-code-from playwright-tests --abort-on-container-exit

      - name: Deploy Allure Report To GitHub Pages
        if: always()
        uses: simple-elf/allure-report-action@v1.11
        with:
          allure_results: reports/allure
          allure_history: allure-history
          keep_reports: 5

      - name: Deploy Report To Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history

      - name: Upload Allure Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./reports/allure/

      - name: Tear Down Containers
        if: always()
        working-directory: ./docker
        run: docker compose down
